name: docs

on:
  # Run using manual triggers from GitHub UI:
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch: {}
  # Run on every push:
  push: {}
  # Run on pull request activity:
  pull_request: {}

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: build and deploy documentation.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - uses: leanprover/lean-action@v1.0.0
        with:
          use-mathlib-cache: false
          use-github-cache: true

      - uses: Install cadical
      - run: |
          sudo apt-get install -y cadical

      - name: Generate docs 
        run: |
          ./docgen.sh

# Disable documentation uploading until we are happy with our docs.
# stolen from mathlib: https://github.com/leanprover-community/mathlib4_docs/blob/1f4ea7657bc377b4298fd400e567471d3a248b2d/.github/workflows/docs.yaml#L79-L86
#       - name: Upload artifact üìÅ
#         uses: actions/upload-pages-artifact@v1
#         with:
#           path: '.lake/build/doc'
#
#       - name: Deploy to GitHub Pages üöÄ
#         id: deployment
#         uses: actions/deploy-pages@v1
